TERMUX_PKG_HOMEPAGE=https://jpmens.net/2016/03/05/a-shell-command-to-create-json-jo/
TERMUX_PKG_DESCRIPTION="JSON output from a shell"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.4
TERMUX_PKG_REVISION=2
